apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  # образы в ghcr.io публичные, поэтому достаточно анонимной записи auths
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7fX19
type: kubernetes.io/dockerconfigjson
